# Generated by Django 2.1.5 on 2019-01-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('answerTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='chat.Line')),
                ('functions', models.ManyToManyField(blank=True, related_name='lines', to='chat.EvaluationFunction')),
            ],
        ),
        migrations.CreateModel(
            name='LinePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('altParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altChildren', to='chat.LinePiece')),
                ('functions', models.ManyToManyField(blank=True, related_name='linePieces', to='chat.EvaluationFunction')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chat.LinePiece')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuperTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('opposite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.SuperTrait')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('speaker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='chat.Speaker')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chat.SuperTrait')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='pieces',
            field=models.ManyToManyField(to='chat.LinePiece'),
        ),
        migrations.AddField(
            model_name='line',
            name='startsConversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Conversation'),
        ),
        migrations.AddField(
            model_name='evaluationfunction',
            name='trait',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='chat.SuperTrait'),
        ),
    ]
