# Generated by Django 2.1.5 on 2019-02-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_linepiece_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linepiece',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
