# Generated by Django 2.1.5 on 2019-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190201_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertrait',
            name='group',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
