# Generated by Django 3.0.8 on 2020-10-04 17:08

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190212_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluationfunction',
            name='type',
            field=models.CharField(choices=[('TR', 'TRAIT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='startsConversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startline', to='chat.Conversation'),
        ),
        migrations.AlterField(
            model_name='linepiece',
            name='text',
            field=chat.models.NonStrippingTextField(blank=True),
        ),
    ]
