# Generated by Django 3.0.8 on 2020-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20201004_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationfunction',
            name='type',
            field=models.CharField(choices=[('TR', 'TRAIT'), ('RAW', 'RAW')], max_length=10),
        ),
    ]
