# Generated by Django 3.0.8 on 2020-10-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20201007_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='answerTo_extra',
        ),
    ]
