# Generated by Django 3.0.8 on 2020-10-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_line_answerto_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='answerTo_extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_extra', to='chat.Line'),
        ),
    ]
